version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "edicarloslds"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore major version updates for stable dependencies
      # They will be handled manually
      - dependency-name: "@modelcontextprotocol/sdk"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci:"
    reviewers:
      - "edicarloslds"
    allow:
      - dependency-type: "all"
