export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: './jest-environment-node-no-localstorage.cjs',
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^(\\.\\.?/.*)\\.js$': '$1',
    '^@client/(.+?)\\.js$': '<rootDir>/src/client/$1',
    '^@client/(.+)$': '<rootDir>/src/client/$1',
    '^@config/(.+?)\\.js$': '<rootDir>/src/config/$1',
    '^@config/(.+)$': '<rootDir>/src/config/$1',
    '^@schemas/(.+?)\\.js$': '<rootDir>/src/schemas/$1',
    '^@schemas/(.+)$': '<rootDir>/src/schemas/$1',
    '^@services/(.+?)\\.js$': '<rootDir>/src/services/$1',
    '^@services/(.+)$': '<rootDir>/src/services/$1',
    '^@defs/(.+?)\\.js$': '<rootDir>/src/types/$1',
    '^@defs/(.+)$': '<rootDir>/src/types/$1',
    '^@utils/(.+?)\\.js$': '<rootDir>/src/utils/$1',
    '^@utils/(.+)$': '<rootDir>/src/utils/$1',
    '^@server/(.+?)\\.js$': '<rootDir>/src/server/$1',
    '^@server/(.+)$': '<rootDir>/src/server/$1',
  },
  testPathIgnorePatterns: ['/__mocks__/'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: {
          module: 'es2020',
          baseUrl: '.',
          paths: {
            '@client/*': ['src/client/*'],
            '@config/*': ['src/config/*'],
            '@schemas/*': ['src/schemas/*'],
            '@services/*': ['src/services/*'],
            '@defs/*': ['src/types/*'],
            '@utils/*': ['src/utils/*'],
            '@server/*': ['src/server/*'],
          },
          noImplicitAny: false,
          strict: false,
        },
        diagnostics: false,
      },
    ],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(p-limit|yocto-queue|lru-cache))',
  ],
  testMatch: ['**/test/unit/**/*.test.ts'],
  collectCoverageFrom: ['src/**/*.ts'],
  coveragePathIgnorePatterns: ['/node_modules/', '/dist/'],
};
